project:
  type: website
  output-dir: docs
  resources:
    - syllabi/
    - pdfs/
    - assignment_1_files/
    - assignment_2_files/
    - Assignment 2/
    - past_work/

website:
  title: "Graduate Work Product"
  search: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: Coursework
        menu:
          - text: "KNOWLEDGE MINING"
          - href: syllabi/knowledge_mining_syllabus.pdf
            text: "--- Syllabus"
          - href: knowledge_mining_notes.qmd
            text: "--- Lecture Notes"
          - text: "---"
          - text: "ASSIGNMENT 1"
          - href: assignment_1_files/Lab01.html
            text: "   Lab 01: Report"
          - href: assignment_1_files/Lab02.html
            text: "   Lab 02: Report"
          - text: "---"
          - text: "ASSIGNMENT 2"
          - href: Assignment 2/assignment_2.html
            text: "   Systematic Literature Review"
          - text: "---"
          - href: assigned_reading.qmd
            text: "Assigned Reading"
          - text: "---"
          - text: "QUANTITATIVE METHODS"
          - href: syllabi/quantitative_methods_syllabus.pdf
            text: "--- Syllabus"
          - href: quantitative_meth